### ISSUE TITLE
Remove this repo and use the wiki repo instead of it

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_doc#1]
It's a bit weird to have 2 different repos for docs. I has been looking for docs in wiki, which misses some info present here. Could you move the info from this repo to the wiki, please (you can also include the wiki as a submodule because wikis on GH are also git repos)?

**Comment by GreyCat** [comment]
The plan was actually to do vice versa: replace wiki content with links and have a proper documentation web site with sources, formatting, etc.
